### ISSUE TITLE
Can install via npm

### ISSUE THREAD

**Issue by ewal** [cloudinary/cloudinary-react#1]
Hi, I currently get this message when trying to install:

`npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cloudinary-react`

**Comment by roeeba** [comment]
Hi @ewal, we seem to be able to install the package on our end. Are you still facing this issue? if so, can you please let us know how can we reproduce it?

**Comment by ewal** [comment]
Hi, still can't install.
Log below:

```
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/ewal/.nvm/versions/node/v5.12.0/bin/node" "/Users/ewal/.nvm/versions/node/v5.12.0/bin/npm" "install" "cloudinary-react" "--save"
npm ERR! node v5.12.0
npm ERR! npm  v3.10.8
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/cloudinary-react
npm ERR! 404
npm ERR! 404  'cloudinary-react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by roeeba** [comment]
Sorry @ewal , you're obviously right. We are working on resolving it now. 
Update to follow.

**Comment by roeeba** [comment]
Hi @ewal , The issue has been resolved. Please try again and let us know?

**Comment by ewal** [comment]
Managed to install now 👍

**Comment by Devendra-Raj-Sharma** [comment]
how to install cloudnary

PS C:\Users\DEVENDRA RAJ SHARMA\Desktop\Project> npm i cloudnary
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cloudnary - Not found
npm ERR! 404 
npm ERR! 404  'cloudnary@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DEVENDRA RAJ SHARMA\AppData\Local\npm-cache\_logs\2021-09-20T11_11_13_100Z-debug.log

**Comment by Vdeub-cloudinary** [comment]
Hi @Devendra-Raj-Sharma, you are missing a `i` in `cloudinary`.

Can you please try the command below?
```npm i cloudinary```
