### ISSUE TITLE
Consider using React.createContext instead of the legacy context API

### ISSUE THREAD

**Issue by bernharduw** [cloudinary/cloudinary-react#113]
When enabling strict mode checks in React, React throws warnings about CloudinaryContext using legacy context APIs, with this link to more information: https://fb.me/react-strict-mode-warnings

Consider refactoring this in the near future as the old context API will be unsupported in the next major React version.

More info here: https://reactjs.org/docs/context.html#legacy-api

**Comment by maoznir** [comment]
Thanks @bernharduw we're considering upgrading the react peer dependency to ^16.3 (not 16.8 yet for as broad support as possible) and replace all deprecated life cycle methods and context api in the next major release.

**Comment by bernharduw** [comment]
Awesome - makes sense, thanks!

**Comment by idirocco** [comment]
@maoznir Do you have a ERD? Thanks!

**Comment by maoznir** [comment]
Closing as this was handled in version 1.2.0
