### ISSUE TITLE
cloudinary-core error

### ISSUE THREAD

**Issue by shouvik44** [cloudinary/cloudinary-react#114]
I started getting this build error today, and so did the other developer on my team. We haven't made changes to Cloudinary, so curious if you have any advice.

Module not found: Error: Can't resolve 'cloudinary-core' in '/Users/shouvikbanerjee/GitHub/averpointMERN/node_modules/cloudinary-react/lib/components/CloudinaryContext'

**Comment by maoznir** [comment]
Hi @shouvik44 please reinstall cloudinary-react. there was a problem with cloudinary-core that is now fixed in version 2.7.2 of cloudinary-core.
