### ISSUE TITLE
Cannot destructure property `compile` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by jldivemaster** [cloudinary/cloudinary-react#125]
Ran "npm install" then "npm start" in the photo-album sample and getting the above error.  Full error log is below:

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/flatironschool/.nvm/versions/node/v12.8.0/bin/node',
1 verbose cli   '/Users/flatironschool/.nvm/versions/node/v12.8.0/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle photo_album@0.1.0~prestart: photo_album@0.1.0
6 info lifecycle photo_album@0.1.0~start: photo_album@0.1.0
7 verbose lifecycle photo_album@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle photo_album@0.1.0~start: PATH: /Users/flatironschool/.nvm/versions/node/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/flatironschool/Development/references/cloudinary-react/samples/photo_album/node_modules/.bin:/Users/flatironschool/.nvm/versions/node/v12.8.0/bin:/Users/flatironschool/.rvm/gems/ruby-2.6.1/bin:/Users/flatironschool/.rvm/gems/ruby-2.6.1@global/bin:/Users/flatironschool/.rvm/rubies/ruby-2.6.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/flatironschool/.platformio/penv/bin:/Users/flatironschool/.platformio/penv:/Users/flatironschool/.rvm/gems/ruby-2.6.1/bin:/Users/flatironschool/.rvm/gems/ruby-2.6.1@global/bin:/Users/flatironschool/.rvm/rubies/ruby-2.6.1/bin:/Users/flatironschool/.rvm/bin:/Users/flatironschool/.rvm/bin
9 verbose lifecycle photo_album@0.1.0~start: CWD: /Users/flatironschool/Development/references/cloudinary-react/samples/photo_album
10 silly lifecycle photo_album@0.1.0~start: Args: [ '-c', 'node scripts/start.js' ]
11 silly lifecycle photo_album@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle photo_album@0.1.0~start: Failed to exec start script
13 verbose stack Error: photo_album@0.1.0 start: `node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/flatironschool/.nvm/versions/node/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/flatironschool/.nvm/versions/node/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid photo_album@0.1.0
15 verbose cwd /Users/flatironschool/Development/references/cloudinary-react/samples/photo_album
16 verbose Darwin 18.7.0
17 verbose argv "/Users/flatironschool/.nvm/versions/node/v12.8.0/bin/node" "/Users/flatironschool/.nvm/versions/node/v12.8.0/bin/npm" "start"
18 verbose node v12.8.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error photo_album@0.1.0 start: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the photo_album@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

Thanks for any help!

**Comment by maoznir** [comment]
Hi @jldivemaster,

Thanks for letting us know, we're planning to fix that.
I'll update when we do.

**Comment by maoznir** [comment]
Hi @jldivemaster I've merged a fix for this:
https://github.com/cloudinary/cloudinary-react/pull/128/commits/e6a2d0300044e5a4a5bd1ef3f81c814de545bd3b
