### ISSUE TITLE
Is there any way to lazy load image & specify placeholder color while image is loading?

### ISSUE THREAD

**Issue by Shahzayb** [cloudinary/cloudinary-react#132]

**Comment by Shahzayb** [comment]
`                <Image
                    cloudName={process.env.REACT_APP_CLOUDINARY_CLOUD_NAME}
                    dpr="auto"
                    responsive
                    width="auto"
                    crop="fit"
                    sizes="(min-width: 992px) 34vw,
                           (max-width: 992px) 50vw,
                           (max-width: 768px) 100vw"
                    publicId={obj.publicId}
                    secure={true}
                  >
                    <Transformation quality="auto" fetchFormat="auto" />
                  </Image>
`

I want to specify the grey color placeholder while the image is loading.

**Comment by Shahzayb** [comment]
`<Image`
                   `   cloudName={process.env.REACT_APP_CLOUDINARY_CLOUD_NAME}`
                    `  dpr="auto"`
                    `  responsive`
                   `   width="auto"`
                    `  crop="fit"`
                   `   sizes="(min-width: 992px) 34vw,`
                         `      (max-width: 992px) 50vw,`
                          `     (max-width: 768px) 100vw"`
                 `     publicId={obj.publicId}`
                  `    secure={true}>`
                    `    <Transformation quality="auto" fetchFormat="auto" />`
                `  </Image>`

I want to specify a grey color while the image is loading.

**Comment by maoznir** [comment]
Hi @Shahzayb 
Those features do not exist yet in the React SDK, but they are in our road-map.
Until then, maybe you can try something along the lines of this:
https://stackblitz.com/edit/cloudinary-react-placeholder-example-with-color
