### ISSUE TITLE
CORS problem > Firefox and Safari

### ISSUE THREAD

**Issue by cyruslk** [cloudinary/cloudinary-react#135]
Hey there, 

Here's the App I'm working on:  cooing-sugar.surge.sh

When I'm fetching your images using `axios`, I have cors issues on `Firefox` and on `Safari` and only onClick. I'm tried to overcome CORS from my react app using:

```
  const config = {
      headers: {
        'Access-Control-Allow-Origin': '*',
     }
   };

axios.get(`https://cors-anywhere.herokuapp.com/${spreadsheetURL}`, config)
.then((response) => {
....
)}

```

Problem on firefox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://res.cloudinary.com/dcpexd0zo/image/upload/v157136216…pes/Capture_d_e%CC%81cran_le_2019-10-17_a%CC%80_21.26.11.jpg. (Reason: missing token ‘user-agent’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://res.cloudinary.com/dcpexd0zo/image/upload/v157136216…pes/Capture_d_e%CC%81cran_le_2019-10-17_a%CC%80_21.26.11.jpg. (Reason: CORS request did not succeed).

TypeError: NetworkError when attempting to fetch resource.
```

Problem on safari:

```
Request header field User-Agent is not allowed by Access-Control-Allow-Headers.

Fetch API cannot load https://res.cloudinary.com/dcpexd0zo/image/upload/v1571362166/shapes/Capture_d_e%CC%81cran_le_2019-10-17_a%CC%80_21.26.11.jpg due to access control checks.

https://res.cloudinary.com/dcpexd0zo/image/upload/v1571362166/shapes/Capture_d_e%CC%81cran_le_2019-10-17_a%CC%80_21.26.11.jpg Failed to load resource: Request header field User-Agent is not allowed by Access-Control-Allow-Headers.

Error: The error you provided does not contain a stack trace.

Unhandled Promise Rejection: TypeError: Request header field User-Agent is not allowed by Access-Control-Allow-Headers.
```

**Comment by aleksandar-cloudinary** [comment]
Hi @cyruslk. By default, Cloudinary doesn't set any CORS restrictions on origin when requesting resources. As a result, you can just request the resource directly from Cloudinary rather than going through the cors-app. May I please ask if there's any reason you're going down this route and to try setting the source of the GET to ${spreadsheetURL}?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by CaptainN** [comment]
This is still a problem. Disabling the user-agent request header in the library does fix it.

**Comment by shirlymanor** [comment]
@CaptainN if that issue still accrues please contact us at support@clouddinary.com.
