### ISSUE TITLE
Responsive hook for URLs to set background images

### ISSUE THREAD

**Issue by sanny-io** [cloudinary/cloudinary-react#137]
From my understanding, there is no support for background images. However, this can be achieved without too much trouble. If the `Image` component is changed to be functional instead of class based, the responsive functionality could be extracted into a hook that would provide `Image` with the appropriate URL.

What this would do is also allow the community to do things like set `background` CSS properties to have a responsive background image.

```javascript
function MyComponent() {
    const responsiveImageUrl = useResponsiveImage(options);
    // ...
}
```

**Comment by maoznir** [comment]
Hi @sanny-io,
Thank you for the suggestion. Cloudinary React SDK's minimum supported React version is 16.3.3, therefore React hooks are not included.
In a future major version we might update to newest React version that includes hooks.
Meanwhile you could use Cloudinary Core (https://www.npmjs.com/package/cloudinary-core) to generate a url and use that in your component.

**Comment by sanny-io** [comment]
I see, that makes sense.
