### ISSUE TITLE
Using format f_auto

### ISSUE THREAD

**Issue by jeremyk** [cloudinary/cloudinary-react#14]
I can't seem to figure out how to do this with props.

http://cloudinary.com/blog/transparent_webp_format_cdn_delivery_based_on_visitors_browsers

Thanks,
Jeremy

**Comment by eitanp461** [comment]
@jeremyk Take a look at this Codepen project - https://codepen.io/eitanp461/project/editor/ANWPqL/#

The gist of it is using `fetch-format="auto"` as in the following example:

```
<Image publicId="sample">
    <Transformation fetch-format="auto" width="200" crop="scale" angle="10"/>
</Image>
```

The result image URL is https://res.cloudinary.com/demo/image/upload/a_10,c_scale,f_auto,w_200/sample
