### ISSUE TITLE
How to disable the video download and picture in picture buttons ?

### ISSUE THREAD

**Issue by bogdan-around** [cloudinary/cloudinary-react#141]
I need to disable the download and picture in picture buttons from the Video component. I have tried to look at the documentation but I was not able to see anything related to this.

**Comment by shirlymanor** [comment]
@bogdan-around If you're seeing the download link in Chrome's native player, you can disable the download link by adding controlsList="nodownload" to the video tag.
For more information please see here: https://googlechrome.github.io/samples/media/controlslist.html
Alternatively, you can use Cloudinary video player which don't have the download button. You can read more about it here: https://cloudinary.com/documentation/cloudinary_video_player Please notes that any public video can be downloaded (even without the button).

**Comment by bogdan-around** [comment]
Thank you allot for the resources provided. I have managed to disable download and picutreInpicture by using the following : 
`<Video
    cloudName={myCloudName}
    publicId={videoId}
    autoPlay={true}
    controls={true}
    width="100%"
    height="100%"
    disablePictureInPicture
    controlsList="nodownload"
  />`
