### ISSUE TITLE
Misspelling of "deployed"

### ISSUE THREAD

**Issue by janzenisaac** [cloudinary/cloudinary-react#142]
Small comment, but under `running` _deployed_ is spelled incorrectly.

**Comment by eyalktCloudinary** [comment]
Hey @janzenisaac, thank you for the feedback! Can you please share more information about the issue? Where do you see the typo?

**Comment by janzenisaac** [comment]
https://github.com/cloudinary/cloudinary-react/blob/master/samples/photo_album/README.md#running

**Comment by shirlymanor** [comment]
Thank you for your feedback!
We created a PR to fix this.
