### ISSUE TITLE
Error: .field(name, val) val can not be empty 

### ISSUE THREAD

**Issue by rleslie1015** [cloudinary/cloudinary-react#144]
I am trying to upload to my cloudinary account with the Photo album sample and the errror I get after following the configuration steps is `cloudinary-react/samples/photo_album/`.  The error points to line 108 in PhotoUploader.js

**Comment by shirlymanor** [comment]
Can you please share more details about the error message? do you have your code online for us to test? if privacy is an issue you can open a ticket at support@cloudinary.com.

**Comment by rleslie1015** [comment]
The code is already online inside the photo album sample `cloudinary-react/samples/photo_album/src/components/PhotosUploader.js` the error is there after forking it and changing the configurations the readMe talks about. The error points to `cloudinary-react/samples/photo_album/src/components/PhotosUploader.js`. When I try to upload a photo it gives the error. The error points [to this file](https://github.com/cloudinary/cloudinary-react/blob/master/samples/photo_album/src/components/PhotosUploader.js). lines 99 to one 120. Can you just explain what this code is doing? `
    onPhotoSelected(files) {
        const url = `https://api.cloudinary.com/v1_1/${
            this.context.cloudName
            }/upload`;
        const title = this.titleEl.value;

        for (let file of files) {
            const photoId = this.photoId++;
            const fileName = file.name;
            request.post(url)
                .field('upload_preset', this.context.uploadPreset)
                .field('file', file)
                .field('multiple', true)
                .field('tags', title ? `myphotoalbum,${title}` : 'myphotoalbum')
                .field('context', title ? `photo=${title}` : '')
                .on('progress', (progress) => this.onPhotoUploadProgress(photoId, file.name, progress))
                .end((error, response) => {
                    this.onPhotoUploaded(photoId, fileName, response);
                });
        }
    }

`

**Comment by maoznir** [comment]
@rleslie1015 Thanks for pointing this out, we're working on a fix.
I'll update when it's done

**Comment by maoznir** [comment]
@rleslie1015 This is now fixed in version 1.3.1 and up, please let us know if it works fo you.
