### ISSUE TITLE
fetch_format="auto" on cloudinary-context doesn't apply to components down the tree

### ISSUE THREAD

**Issue by brad-decker** [cloudinary/cloudinary-react#15]
#### index.js
```jsx
ReactDOM.render('#div', <CloudinaryContext cloudName="xxxx" fetch_format="auto">
  <App />
</CloudinaryContext>);
```

#### App.js, render method
```jsx
<div>
  <Image publicId="x" width={400} crop="fill" />
</div>
```

The <Image> doesn't have fetch_format=auto applied.

**Comment by eitanp461** [comment]
@brad-decker Thank you for notifying us. 
We will look into why it is not working with `fetch_format`.

In the meantime you can use `fetchFormat="auto"`, see https://codepen.io/eitanp461/project/editor/ZoNNkP/

**Comment by eitanp461** [comment]
Our preferred syntax is `fetchFormat="auto"`. We will update our React docs to reflect this.
