### ISSUE TITLE
is cloudinary-react support typescript?

### ISSUE THREAD

**Issue by itsgracian** [cloudinary/cloudinary-react#151]
Hello!
 
I am using react with typescript but My app is failing to start when I am including this package.
I would like to ask if **cloudinary-react ** support typescript?

**Comment by eyalktCloudinary** [comment]
Hi @itsgracian , thanks for reaching out! Currently, our React SDK does not support typescript. However, we are considering this matter.

**Comment by itsgracian** [comment]
> Hi @itsgracian , thanks for reaching out! Currently, our React SDK does not support typescript. However, we are considering this matter.

Oooh! 
thank you for your response.
