### ISSUE TITLE
TypeError: children is not a function

### ISSUE THREAD

**Issue by vladimirpetukhov** [cloudinary/cloudinary-react#158]
https://github.com/react-dropzone/react-dropzone/releases/tag/v8.0.0
TypeError: children is not a function
(anonymous function)
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dropzone/dist/es/index.js:61
  58 |     };
  59 |   }, [open]); // TODO: Figure out why react-styleguidist cannot create docs if we don't return a jsx element
  60 | 
> 61 |   return React.createElement(Fragment, null, children(_objectSpread({}, props, {
  62 |     open: open
  63 |   })));
  64 | });
View compiled
renderWithHooks
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:14803
  14800 |   }
  14801 | }
  14802 | 
> 14803 | var children = Component(props, secondArg); // Check if there was a render phase update
        | ^  14804 | 
  14805 | if (workInProgress.expirationTime === renderExpirationTime) {
  14806 |   // Keep rendering in a loop for as long as render phase updates continue to
View compiled
updateForwardRef
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:16816
  16813 | {
  16814 |   ReactCurrentOwner$1.current = workInProgress;
  16815 |   setIsRendering(true);
> 16816 |   nextChildren = renderWithHooks(current, workInProgress, render, nextProps, ref, renderExpirationTime);
        | ^  16817 | 
  16818 |   if ( workInProgress.mode & StrictMode) {
  16819 |     // Only double-render components with Hooks
View compiled
beginWork
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:18645
  18642 | 
  18643 |     var _resolvedProps2 = workInProgress.elementType === type ? _unresolvedProps2 : resolveDefaultProps(type, _unresolvedProps2);
  18644 | 
> 18645 |     return updateForwardRef(current, workInProgress, type, _resolvedProps2, renderExpirationTime);
        | ^  18646 |   }
  18647 | 
  18648 | case Fragment:
View compiled
HTMLUnknownElement.callCallback
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:188
  185 |     window.event = windowEvent;
  186 |   }
  187 | 
> 188 |   func.apply(context, funcArgs);
      | ^  189 |   didError = false;
  190 | } // Create a global error event handler. We use this to capture the value
  191 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:237
  234 | // errors, it will trigger our global error handler.
  235 | 
  236 | evt.initEvent(evtType, false, false);
> 237 | fakeNode.dispatchEvent(evt);
      | ^  238 | 
  239 | if (windowEventDescriptor) {
  240 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:292
  289 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  290 |   hasError = false;
  291 |   caughtError = null;
> 292 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  293 | }
  294 | /**
  295 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$1
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:23203
  23200 | } // Run beginWork again.
  23201 | 
  23202 | 
> 23203 | invokeGuardedCallback(null, beginWork, null, current, unitOfWork, expirationTime);
        | ^  23204 | 
  23205 | if (hasCaughtError()) {
  23206 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:22154
  22151 | 
  22152 | if ( (unitOfWork.mode & ProfileMode) !== NoMode) {
  22153 |   startProfilerTimer(unitOfWork);
> 22154 |   next = beginWork$1(current, unitOfWork, renderExpirationTime$1);
        | ^  22155 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  22156 | } else {
  22157 |   next = beginWork$1(current, unitOfWork, renderExpirationTime$1);
View compiled
workLoopSync
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:22130
  22127 | function workLoopSync() {
  22128 |   // Already timed out, so perform work without checking if we need to yield.
  22129 |   while (workInProgress !== null) {
> 22130 |     workInProgress = performUnitOfWork(workInProgress);
  22131 |   }
  22132 | }
  22133 | /** @noinline */
View compiled
performSyncWorkOnRoot
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:21756
  21753 | 
  21754 | do {
  21755 |   try {
> 21756 |     workLoopSync();
        | ^  21757 |     break;
  21758 |   } catch (thrownValue) {
  21759 |     handleError(root, thrownValue);
View compiled
scheduleUpdateOnFiber
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:21188
  21185 |   // root inside of batchedUpdates should be synchronous, but layout updates
  21186 |   // should be deferred until the end of the batch.
  21187 | 
> 21188 |   performSyncWorkOnRoot(root);
        | ^  21189 | } else {
  21190 |   ensureRootIsScheduled(root);
  21191 |   schedulePendingInteractions(root, expirationTime);
View compiled
updateContainer
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:24373
  24370 |   }
  24371 | 
  24372 |   enqueueUpdate(current$1, update);
> 24373 |   scheduleWork(current$1, expirationTime);
  24374 |   return expirationTime;
  24375 | }
  24376 | function getPublicRootInstance(container) {
View compiled
(anonymous function)
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:24758
  24755 | 
  24756 | 
  24757 |   unbatchedUpdates(function () {
> 24758 |     updateContainer(children, fiberRoot, parentComponent, callback);
        | ^  24759 |   });
  24760 | } else {
  24761 |   fiberRoot = root._internalRoot;
View compiled
unbatchedUpdates
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:21903
  21900 | executionContext |= LegacyUnbatchedContext;
  21901 | 
  21902 | try {
> 21903 |   return fn(a);
        | ^  21904 | } finally {
  21905 |   executionContext = prevExecutionContext;
  21906 | 
View compiled
legacyRenderSubtreeIntoContainer
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:24757
  24754 |   } // Initial mount should not be batched.
  24755 | 
  24756 | 
> 24757 |   unbatchedUpdates(function () {
        | ^  24758 |     updateContainer(children, fiberRoot, parentComponent, callback);
  24759 |   });
  24760 | } else {
View compiled
render
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/node_modules/react-dom/cjs/react-dom.development.js:24840
  24837 |     }
  24838 |   }
  24839 | 
> 24840 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  24841 | }
  24842 | function unstable_renderSubtreeIntoContainer(parentComponent, element, containerNode, callback) {
  24843 |   if (!isValidContainer(containerNode)) {
View compiled
Module../src/index.js
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/src/index.js:29
  26 | 
  27 | const {cloud_name, upload_preset} = config;
  28 | 
> 29 | ReactDOM.render(
  30 | 	<React.StrictMode>
  31 | 		<Provider store={store}>
  32 | 			<App cloudName={cloud_name} uploadPreset={upload_preset} />
View compiled
__webpack_require__
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
fn
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/webpack/bootstrap:150
  147 | 		);
  148 | 		hotCurrentParents = [];
  149 | 	}
> 150 | 	return __webpack_require__(request);
      | ^  151 | };
  152 | var ObjectFactory = function ObjectFactory(name) {
  153 | 	return {
View compiled
1
http://localhost:3000/static/js/main.chunk.js:3780:18
__webpack_require__
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/webpack/bootstrap:784
  781 | };
  782 | 
  783 | // Execute the module function
> 784 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  785 | 
  786 | // Flag the module as loaded
  787 | module.l = true;
View compiled
checkDeferredModules
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/webpack/bootstrap:45
  42 | 	}
  43 | 	if(fulfilled) {
  44 | 		deferredModules.splice(i--, 1);
> 45 | 		result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
     | ^  46 | 	}
  47 | }
  48 | 
View compiled
Array.webpackJsonpCallback [as push]
C:/Apps/ReactJs/CakeOrdersAttestation/cakeorders/webpack/bootstrap:32
  29 | 	deferredModules.push.apply(deferredModules, executeModules || []);
  30 | 
  31 | 	// run deferred modules when all chunks ready
> 32 | 	return checkDeferredModules();
     | ^  33 | };
  34 | function checkDeferredModules() {
  35 | 	var result;
View compiled
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:73
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by patrick-tolosa** [comment]
@vladimirpetukhov  - What exactly is the issue you want to report?
Please edit the issue to reflect the problem your facing.
