### ISSUE TITLE
1.5.1 broken in Safari

### ISSUE THREAD

**Issue by mcmillion** [cloudinary/cloudinary-react#169]
Getting the following error in Safari (latest): `SyntaxError: Invalid regular expression: invalid group specifier name`

Looks like this actually may be inside `cloudinary-core`? We got this issue after recently updating to `cloudinary-react` to 1.5.1. Initial digging looks like this is an issue with Safari not supporting regex lookbehind.

## Steps to reproduce
Use Safari. Tested on 13.1.1, but it looks like any version of Safari will fail.

## Error screenshots
This is minified code, but you can see which regex pattern is at fault
<img width="1369" alt="Screen Shot 2020-06-30 at 3 34 52 PM" src="https://user-images.githubusercontent.com/717799/86174468-51c07300-bae7-11ea-80f1-1d874d9fc8f7.png">

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[X] Safari
[ ] Other (Specify)
[ ] All

**Comment by shirlymanor** [comment]
can you please open a ticket at support@cloudinary.com with your cloud name and steps to reproduce the error?

**Comment by maoznir** [comment]
Hi @mcmillion Are you using an Image component? can you please send a code example that causes this for you?

**Comment by mcmillion** [comment]
So the issue is this regex in `cloudinary-core`: https://github.com/cloudinary/cloudinary_js/blob/c6da538d645796a74eac3894d6b0398bfbe90dc9/js/jquery.cloudinary.js#L1490

It's using a regex lookbehind, which is unsupported in Safari.

I can try to find some time to work on a reproduction, but essentially just calling this regex at all will fail in Safari.

**Comment by maoznir** [comment]
@mcmillion I cannot reproduce this with a clean install of cloudinary-react. what version of core is installed in your node_modules?

**Comment by mcmillion** [comment]
2.9.0

**Comment by patrick-tolosa** [comment]
Hey @mcmillion 

The file you posted from `cloudinary-core` is called jquery.cloudinary.js, how are you using this file?

In general, the import path should look something like this: `import {Image} from 'cloudinary-react' `, are you using anything different? 

Can you also please confirm the problem still persists after a clean npm install?

Finally, if you could provide us with a minimal repro that would be great.

**Comment by maoznir** [comment]
Hi @mcmillion 
In addition to @patrick-tolosa comment, i'd like to update that new cloudinary-react version 1.6.0 was released that uses an updated cloudinary-core, please let us know if that also might solve the issue for you.

**Comment by mcmillion** [comment]
Yep, the update fixes the regex issue for me (and introduces another, I'll make another issue). Thanks!

**Comment by maoznir** [comment]
@mcmillion I'd still be very happy to understand how you're getting to that file in the js folder, which isn't supposed to be part of the sdk
