### ISSUE TITLE
data-testid being mangled into datatestid

### ISSUE THREAD

**Issue by mcmillion** [cloudinary/cloudinary-react#178]
## Describe the bug in a sentence or two.

Previously, adding a `data-testid` to an `Image` component worked. After a previous update, this now get mangled into `datatestid`. I get that this may be unsupported usage, but it's pretty standard in testing, so I wanted to report it.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[X] Other - Testing

## Steps to reproduce
Create an `Image` component and attach a data-attribute to it

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[X] All

**Comment by maoznir** [comment]
Hi @mcmillion thanks for reporting this issue, we'll look into it.

**Comment by maoznir** [comment]
@mcmillion Thanks for letting us know of this issue, it's fixed in version 1.6.2
