### ISSUE TITLE
Image placeholder incorrectly lazy-loaded

### ISSUE THREAD

**Issue by taijuten** [cloudinary/cloudinary-react#186]
## Bug report for Cloudinary React SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
It appears that when defining a placeholder for a lazy-loaded image, the placeholder is also lazy-loaded. contrary to the documentation here: https://cloudinary.com/documentation/react_image_manipulation#image_placeholders

…

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
```
        <Image
          className='img-responsive'
          cloudName='...'
          label={label}
          publicId={src}
          responsive
          loading='lazy'
          width='auto'
          flag='lossy'
          secure
        >
          <Placeholder
            type='blur'
          />
        </Image>
```

## Error screenshots
Please note how the placeholder image below has `data-src` rather than `src`
![Screenshot from 2020-08-02 08-58-44](https://user-images.githubusercontent.com/4288526/89118561-7456fa80-d49e-11ea-93c8-70f96f5bd100.png)

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[x] All

## Versions and Libraries (fill in the version numbers)
React Cloudinary SDK - 1.6.6
React - 16.5.2
Create-React-App - 3.4.1

**Comment by shirlymanor** [comment]
@taijuten Can you please check that it's working for you? Here is a sample code:  https://codesandbox.io/s/gracious-smoke-psy0u?file=/src/App.js

**Comment by taijuten** [comment]
Hi @shirlymanor,

This snippet itself isn't enough to reproduce the issue.

I've forked this snippet and have one showing the issue here.

https://codesandbox.io/s/vibrant-pine-dks7w?file=/src/App.js

If you open your network tab, look at `Img` transfers, and refresh, you'll notice that the placeholder for the second image isn't loaded until it is scrolled to.

This is due to the lazy loading incorrectly being applied to the placeholder.
I've raised a PR to fix this, here: https://github.com/cloudinary/cloudinary-react/pull/189

**Comment by maoznir** [comment]
@taijuten thanks for reporting this, we're looking into this and considering whether this behavior should change, I'll update here as soon as we have a decision.

**Comment by taijuten** [comment]
Thanks @maoznir

I'm only going by the documented behaviour here: https://cloudinary.com/documentation/react_image_manipulation#image_placeholders
> You can also combine placeholder images with the lazy loading feature. In this case, the placeholder image is downloaded on page load, but the target image will only be downloaded once the user scrolls down to the image on the page.

**Comment by ardiewen** [comment]
I thought I'd comment my support for this as well, as I'm experiencing the exact same issue as @taijuten and the way he described it is consistent with the behaviour I'm seeing on my project.

On a product category page for an online store, all the image placeholders on the page should be loaded eagerly creating a "blurred" placeholder, then "blurred up" lazily to the target image.

What actually happens is the placeholder itself will be lazily loaded on scroll, causing a brief flash of whitespace, followed by a brief flash of blurred placeholder image, then followed by the target image load.

**Comment by orteth01** [comment]
Any update on this? my experience is exactly as @ardiewen and @taijuten have described.

**Comment by patrick-tolosa** [comment]
@orteth01  this is currently being discussed internally, the discussion is around whether this behaviour should change.

It looks like we'll keep lazyloading the placeholder.
The reason for this is a use-case of hundreds of images on the page; the browser is limited to 6 requests per domain which can be easily saturated by all the placeholder images.

With regards to the white flashes, we're considering of adding a bigger margin to the bottom of the page, so images will start lazyloading before the viewport reaches them. 

We're also open to suggestions and ideas if you have something else in mind. 

In any case, this is still being discussed internally, we'll update here, and the documentation once a decision is made.

**Comment by heyitstowler** [comment]
@patrick-tolosa What about allowing for hardcoded placeholders to be passed in? For example, with responsive images, I can pass in a data/img string as the `src` and get a placeholder with no network request and then the responsive function will replace it, but lazy only gives me access to the provided placeholder transformations, which require network requests.

**Comment by patrick-tolosa** [comment]
Thanks for the suggestion @heyitstowler , this is something that we might consider adding in future versions.
We're working a new implementation of this area (lazyload, placeholder and such), we'll update once we have more to share.

**Comment by heyitstowler** [comment]
@patrick-tolosa Is there any proposed timeline for this new implementation? Very curious as I'm at a decision point as to whether to use `cloudinary-react`'s lazy loading feature as is vs trying to use a separate tool for lazy loading in tandem with responsive images, and a little more information on timeline would be valuable for making the decision

**Comment by patrick-tolosa** [comment]
@heyitstowler this is a different issue than this thread, so it would be better to discuss it in a separate thread.

We are mixing three different functionalities here : **Responsive**, **Placeholder** and **Lazyload**.

For **lazyload**, it's likely that we will always wait for the lazyload event before loading the placeholder, with some ability to control the gutter and margin of the lazyload functionality.

For **placeholder**, we're considering adding a custom src to act as the low quality placeholder, but we can't provide a date yet.

I'm not sure how **Responsive** is causing issues here though.

**Comment by heyitstowler** [comment]
@patrick-tolosa responsive isn't causing an issue. It just seems to me there should be a way to directly provide a default src to lazy load the same way we can provide a default src to responsive, particularly for the use case of passing a data url so the placeholder doesn't require an additional network request.

**Comment by patrick-tolosa** [comment]
Alright good to know!

We're on the same page regarding the placeholder functionality, we just can't publish any dates at the moment.
We'll publish news on this new development soon enough.

**Comment by maoznir** [comment]
Hi I'd just like to update that eventually we've decided to that for current version we'll keep the current behavior of the placeholder being lazy loaded when loading='lazy', and we've updated the docs accordingly: https://cloudinary.com/documentation/react_image_manipulation#image_placeholders
But we're also working on a new major version, for which we'll consider including options to customize the behavior and hardcoded placeholders.
