### ISSUE TITLE
Lazy Load Offset

### ISSUE THREAD

**Issue by taijuten** [cloudinary/cloudinary-react#187]
## Feature request for Cloudinary React SDK
Similar to Libraries such as [React Lazyload](https://www.npmjs.com/package/react-lazyload#offset) It would be incredibly useful to specify an offset for lazy loading.

## Explain your use case
Loading images when X pixels out of viewport provides a better user experience by increasing chances that the original image has loaded before the user scrolls to it.

## Describe the problem you’re trying to solve
As above

## Do you have a proposed solution?
No, I'm not sure how Cloudinary implements lazyloading behind the scenes.
If using IntersectionObserver, using `rootMargin` and `threshold` would do the trick

**Comment by patrick-tolosa** [comment]
Hey @taijuten 

Thanks for your suggestion, 
We're reviewing this internally and we'll update once we have news.

This somewhat relates to your other issue posted here:
https://github.com/cloudinary/cloudinary_js/issues/255

**Comment by taijuten** [comment]
Thanks for your reply @patrick-tolosa.

It is indeed. It would be super useful to be able to set this, in particular the `threshold`, as if an image is less than 50% in view, won't lazy load. For large images, this is super obvious, and I can see no way in the docs to currently adjust this.

**Comment by maoznir** [comment]
Hi @taijuten 
We are working on a new major version that will include, among other features, support for passing a threshold. 
It is still a work in progress and we're happy to hear any feedback, so if you'd like, you're welcome to try out the beta and let us know whether it meets your expectations:
https://www.npmjs.com/package/@cloudinary/react
https://github.com/cloudinary/frontend-frameworks#readme
