### ISSUE TITLE
Where to find prop documentation

### ISSUE THREAD

**Issue by savybrandt** [cloudinary/cloudinary-react#190]
I'm struggling to find props documentation for any of these components. The storybooks are broken and not displaying prop information and looking directly at the src none of the `propTypes` or `defaultProps` are explicitly listed out. I see no mention in the React section of the documentation either. Where should I be looking for prop documentation? (Thanks in advance!)

**Comment by shirlymanor** [comment]
Here is a link to our documentation: https://cloudinary.com/documentation/react_integration#installation_and_setup

Adding a cloudinary image should look like:

```
import React from 'react'
import {Image, Video, Transformation, CloudinaryContext} from 'cloudinary-react';

const XXXX = () => {
    return (
        <urls>
            <Image 
            cloudName="demo"
            publicId='sample'
            responsive
            dpr="auto"
            height= "700"
            width= "2000"
            crop= "fill"
            />
```
Can you please elaborate on your use-case? for example, you can use defaultProps -  https://github.com/cloudinary/cloudinary-react/blob/96af98be653cf9ae17ecb5db04c392db2f4f119d/src/components/Transformation/Transformation.js#L17
