### ISSUE TITLE
Responsive video player

### ISSUE THREAD

**Issue by donaldboulton** [cloudinary/cloudinary-react#191]
How to make cloudinary video player to be responsive
Tried adding cloudinary core and add use the responsive prop by it is not responsive like the photo gallery. Tried a wrapper with media query's and it does not work.

If I set the width it stays that width on desktop and mobile.

Example code
`
  import React from 'react'
  import {Video, Transformation, CloudinaryContext} from 'cloudinary-react' 
  import {Cloudinary} from 'cloudinary-core';
  const cloudinaryCore = new cloudinary.Cloudinary({cloud_name: 'sample'});

    <CloudinaryContext cloudName="mansbooks">
      {/* Cloudinary Video Player embed code */}
  <Video
    cloudName="demo"
    controls
    responsive
    publicId="dog"
    width="800"
    crop="scale"
    poster={{publicId: 'sample'}}
  />
  </CloudinaryContext>

`

**Comment by eyalktCloudinary** [comment]
Hey @donaldboulton Thanks for reaching out!
It sounds like you're looking for the `fluid` method -
https://cloudinary.com/documentation/video_player_api_reference#fluid
Here is a CodePen example of its usage -
https://codepen.io/eyalkt/pen/oNxpeNE

Kindly let me know if it helps.

**Comment by donaldboulton** [comment]
Works like a charm
Thanks !
Donald Boulton
