### ISSUE TITLE
data- and aria- attributes are passed both correct and incorrectly cause a react-dom error

### ISSUE THREAD

**Issue by mcmillion** [cloudinary/cloudinary-react#195]
## Describe the bug in a sentence or two.
When passing either `data-` or `aria-` attributes, they are passed both as the original hyphenated version _and_ as a camel-cased version. In at least some configurations or versions of react/react-dom, this causes the following error:

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: React does not recognize the `dataTestid` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datatestid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Upon inspection, it looks like both `data-testid` _and_ `dataTestid` are being applied to the `<img>` tag created by `<Image>`. The same appears to be true for `aria-` attributes.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[X] Other (Specify) - Errors in rendered React

## Steps to reproduce
Add a `data-` or `aria-` attribute to `<Image>`

## Versions and Libraries (fill in the version numbers)
React Cloudinary SDK - 1.6.6
React - 16.3.1
Babel - 7.10.2
Node - 12.16.2
NPM - 6.14.4

**Comment by shirlymanor** [comment]
Hi @mcmillion,
Can you please share your code that reproduced the error? 
You can add it here: https://codesandbox.io/s/awesome-architecture-xrgyy?file=/src/App.js

**Comment by maoznir** [comment]
Hi @mcmillion,
Thanks for reporting this issue! we were able to reproduce it, and are working on a fix.
I'll update when a new version with the fix is published to npm.

**Comment by maoznir** [comment]
Hi @mcmillion version 1.6.7 published with a fix for this issue.
Thanks again for reporting this and please let us know that it works for you.
