### ISSUE TITLE
TypeScript Declarations

### ISSUE THREAD

**Issue by AjdinHusic** [cloudinary/cloudinary-react#206]
## Feature request for Cloudinary React SDK
Typescript declaration for all cloudinary react components.

## Explain your use case
When using react with typescript, it is easier to use all imported components with type definitions.

## Describe the problem you’re trying to solve
when importing components into a typescript project, the IDE and the compiler will complain that it is not possible, because of missing type definitions. Rather than finding workarounds, it would be more efficient if these were included out-of-the-box.

## Do you have a proposed solution?
We can either add type definitions in @types npm, or just directly write this react library in typescript which has added benefits:
that way the type versioning will be in sync with the actual source, the source itself will be type safe and after compiling or transpiling, the actual javascript source will be available anyway, so one is not tied to using typescript in their projects even it the original library source was written in it, but they will have better type hinting most likely (depending on their IDE).

**Comment by michalkcloudinay** [comment]
Hi @AjdinHusic, We have an internal request to support typescript in our React SDK. Although I don't have an ETA at the moment, we will keep you posted with new updates.

**Comment by mesolutionsN** [comment]
Same here!

**Comment by michalkcloudinay** [comment]
@mesolutionsN You can try this: https://medium.com/@steveruiz/using-a-javascript-library-without-type-declarations-in-a-typescript-project-3643490015f3 and see if it helps.

**Comment by maoznir** [comment]
Hey @AjdinHusic & @mesolutionsN 
I'm closing this as this feature is unlikely to be developed in the current SDK,
however we are working on a new major version of the SDK, which is developed in typescript.

You can see more here:
https://github.com/cloudinary/cloudinary-js-base
https://github.com/cloudinary/frontend-frameworks#readme

This is still in beta and the syntax and internals might still change, but it's coming soon!
