### ISSUE TITLE
What about background-image?

### ISSUE THREAD

**Issue by laurenskling** [cloudinary/cloudinary-react#21]
The <Image /> now always returns an <img />

But how about background-image's?

**Comment by eitanp461** [comment]
@laurenskling Are you referring to [CSS background-image](https://developer.mozilla.org/en/docs/Web/CSS/background-image?v=example)?

**Comment by laurenskling** [comment]
Yes I am. Sometimes you want to put the image on a div as the background-image (sometimes certain layouts need this). In those cases you want the url to be set as ```<div style={{ backgroundImage: `url(${cloudinaryImage})` }}```. And surely i'd like to be able to use easy to use width and scaling props. So for example having a new prop: ```<Image publicId={myImage} width={300} asBackgroundImage={true} />``` would be lovely,

**Comment by eitanp461** [comment]
You can achieve this with URL manipulation, e.g. in your css/scss file use:
`background-image: url('path-to-cloudinary-image')`

See live example [here](https://plnkr.co/edit/A3RpWXpNXth9cbt9EUDm?p=preview)

You can find the complete [image transformation reference](http://cloudinary.com/documentation/image_transformation_reference) in Cloudinary documentation.

I am not familiar with examples of JSX rendered/translated to CSS properties. If you can share an example of such a component it will be appreciated.

**Comment by laurenskling** [comment]
well, you can also do `<img src='path-to-cloudinary-image' />` so what is the point of this component? :)

I'd like to use these transformations, without having to write that url string myself. Isn't that where this component is aiming at?

We cannot put something in CSS from React, but we can put something in the `style` tag. So in this line you actually render the `img` tag with the `this.state.url` on `src`:
https://github.com/cloudinary/cloudinary-react/blob/master/src/components/Image/Image.js#L111

We can simple render something else here, like: 
```
<div {...attributes} style={{ backgroundImage: `url(${this.state.url})` } ref={(e)=> {this.element = e;}}>
    {this.props.children}
</div>
``` 
But now I think about this, you are already using `children` for your transformations...

**Comment by eitanp461** [comment]
You can use Cloudinary JS SDK for creating the transformations programmatically, e.g.

```
  createBackgroundImage(publicId) {
    const width = 150;
    const t = new cloudinary.Transformation();
    t.angle(20).crop('scale').width(width).aspectRatio('1:1');
    return cloudinaryCore.url(publicId, t);
  }

  render() {
    return (
      <div className="center">
        <div style={{
          width: '150px',
          height: '150px',
          backgroundImage: `url(${this.createBackgroundImage('sample')})`
        }}></div>
    	</div>)
  }
```

See [updated live demo](https://plnkr.co/edit/A3RpWXpNXth9cbt9EUDm?p=preview)

You can find additional examples of using our JS SDK in the [type definition tests file](https://github.com/cloudinary/cloudinary_js/blob/master/types/cloudinary-core-tests.ts)

We do not have plans for JSX-to-CSS transformations.

**Comment by tsi** [comment]
I was looking for this too.
About add ing the js-sdk just to get an image path - it seems like an overkill to send so much JS to get a functionality I already have, just not available to me.
I'd suggest adding a public method to `cloudinary-react` that will return the same value as `this.state.url` of `Image` returns.

**Comment by eitanp461** [comment]
@tsi Cloudinary React SDK depends on Cloudinary's core JS SDK, see https://github.com/cloudinary/cloudinary-react/blob/master/package.json#L45

The React SDK is a thin wrapper on top of the core SDK which adds React components for `Image`, `Transformation` and `Video`. Therefore using the core SDK does not come with an additional cost.

**Comment by tsi** [comment]
@eitanp461 in your demo you're adding:
`  <script src="https://npmcdn.com/cloudinary-core@2.3.0/cloudinary-core-shrinkwrap.js"></script>`
to your page which is a 7700 lines of JS.
This is a lot, can I `import` it in my react component without adding that? how?

**Comment by eitanp461** [comment]
@tsi since `cloudinary-react` already depends on `cloudinary-core` You can use

```
import { CloudinaryContext, Image, Transformation } from 'cloudinary-react';
import cloudinary from 'cloudinary-core';
const cloudinaryCore = new cloudinary.Cloudinary({cloud_name: 'demo'});
```
Without the need to explicitly add `cloudinary-core` to your `package.json`.

See [sample Glitch](https://glitch.com/edit/#!/cloudinary-react-sdk)

**Comment by eitanp461** [comment]
Closing since question was answered. Please open a new issue for continued support if needed.

**Comment by vfonic** [comment]
@eitanp461 Thanks for providing the example! It's a good start, but it really looks more of a hack to me than of an actual solution. There are many ways you can make this much much easier for us, users.

Here are some, some are terrible, but my opinion is that all of the below given solutions are better than to have a private method, outside of the library.

One more reason for having it as part of the library is the reusability of `Transformation` component. And that's actually what I'm looking for as I have some places where I'm using the same image, once as background image and other time as img tag. I'd like to be able to call the same / similar function/component in which I would be able to reuse my Transformation component. With the above solution, it's only possible if I use the private method in both cases.

```jsx
var backgroundImageUrl = (<Image cloudName="cloud_demo" publicId={publicId} responsive withoutTag={true}>
      <Transformation
        crop={crop}
        width={width}
        height={height}
        dpr="auto"
      />
    </Image>);
```

```jsx
var backgroundImageUrl = (<ImageUrl cloudName="cloud_demo" publicId={publicId} responsive>
      <Transformation
        crop={crop}
        width={width}
        height={height}
        dpr="auto"
      />
    </ImageUrl>);
```

```jsx
<Image cloudName="cloud_demo" publicId={publicId} responsive tagName="div">
      <Transformation
        crop={crop}
        width={width}
        height={height}
        dpr="auto"
      />
    </Image>
```

**Comment by shirlymanor** [comment]
Thank you for sharing your code!

Currently, we are not supporting a React component that renders JSX to a background image in CSS.
I've passed it on to our product-team to have a look at this as a feature request. there's no ETA yet.
Thanks,

**Comment by GaddMaster** [comment]
Theres an easy way for achieveing this. Im about to undertake it. 

// This is just example idea
const myCloudinaryPath = "www.cloudinary.com/username/folder/";
const publicId = props.image.publicId;

```
<div style = {{ backgroundImage: myCloudinaryPath + publicId }}>
  <div>Text</div>
  <div>Text</div>
</div>
```

I think this will work, I am about to try it now anyways ... hehe

**Comment by vfonic** [comment]
@GaddMaster how do you apply any transformations to your image? If I'm trying to render a small thumbnail 100x100px, for example for user avatar/profile pic, if I use your methods, it will render the full size image that was uploaded to cloudinary, right?

So, the user can upload 2000x2000px profile image and that will now render in this small square and unnecessarily cost page visitors their bandwidth and time to download.

**Comment by GaddMaster** [comment]
@vfonic make a avatar folder with that small res images. No transformations. Plain and simple

**Comment by vfonic** [comment]
:joy: that is killing the whole purpose of Cloudinary as a business.

**Comment by GaddMaster** [comment]
@vfonic Still fast cdn request left ! :)

**Comment by GaddMaster** [comment]
@vfonic I am having this same issue as I want to have a number in middle of the image. Might be another way , let me check

**Comment by vfonic** [comment]
@eitanp461 do you think this should be reopened now?

**Comment by eyalktCloudinary** [comment]
@vfonic Hey, Can you clarify what feature are you missing?
 Please refer to [this link](https://www.10bis.co.il/next/Restaurants/Search/Delivery/17-23109-20-3757211). It has several examples such as

```
<Image publicId="mypic">
  <Transformation height="150" width="150" crop="fill" effect="sepia" radius="20" />
  <Transformation overlay="text:arial_60:This is my picture" gravity="north" y="20" />
  <Transformation angle="20" />
</Image>
```
Is that what you're looking for?

**Comment by Ahlambey** [comment]
@eyalktCloudinary the code you wrote doesn't work when we use the image as a background image.

**Comment by eyalktCloudinary** [comment]
Fixed the link in my previous comment.
@Ahlambey Yes, you are right, the code I've added creates an image tag. As @eitanp461 mentioned [here](https://github.com/cloudinary/cloudinary-react/issues/21#issuecomment-304544944), you can generate an image URL with the JS SDK's (which the React SDK is built upon) [url() method](https://cloudinary.com/documentation/react_integration#using_core_cloudinary_javascript_features). Currently, this is the only option for generating an image URL.
