### ISSUE TITLE
sourceTypes incorrectly adding video as mimetype when using codec

### ISSUE THREAD

**Issue by ajonp** [cloudinary/cloudinary-react#210]
## Describe the bug in a sentence or two.
When using sourceTypes and trying to use codecs like    `sourceTypes={['hls', 'webm', 'mp4/h265', 'mp4']}`
it strips out the h265 from the list and just tries to add `video/mp4`

## Describe the desired/expected behavior.
The mime types should allow for all of the sourcetypes and codecs.

## Link to reproduction of the issue on codepen/jsfiddle/etc.
…

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[ ] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ ] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary-core - 0.0.0
Cloudinary-react - 0.0.0
React - 0.0.0
Create-React-App - 0.0.0 / N/A
Babel - 0.0.0
Webpack/Rollup/Other - 0.0.0
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json
Webpack.config (if applicable)
Babelrc

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

https://github.com/cloudinary/cloudinary-react/blob/3ab70fafce7d12bbd3016cd8d20025a0e2e52477/src/components/Video/Video.js#L49

**Comment by michalkcloudinay** [comment]
Hi @ajonp, Thanks for contacting us. If the video is too large to transform on-the-fly and the derived version wasn't generated ahead of time, you would receive the original format (mp4). In order to further investigate, can you please provide the URL of the video you are trying to play? If privacy is a concern you can open a ticket at support@cloudinary.com. Thanks

**Comment by maoznir** [comment]
Hi @ajonp thanks again for bringing this issue to our attention, we'll look into this.
Meanwhile I'd like to suggest a workaround: you can use the sources prop instead of sourceTypes like this:
Please let me know if that solves the issue for you.

```
<Video
  cloudName='demo'
  publicId='dog'
  sources={[
    {
      type: 'mp4',
      codecs: 'hev1',
      transformations: { videoCodec: 'h265' }
    },...]}
/>

```
Will produce:
```
<video poster="http://res.cloudinary.com/demo/video/upload/dog.jpg">
	<source src="http://res.cloudinary.com/demo/video/upload/vc_h265/dog.mp4" type="video/mp4; codecs=hev1"/>
</video>
```

**Comment by maoznir** [comment]
Hi @ajonp I'd like to update that the workaround I've suggested is actually the recommended way to go about defining the codec. please let us know if it works for you.
