### ISSUE TITLE
Image gallery?

### ISSUE THREAD

**Issue by Dashue** [cloudinary/cloudinary-react#226]
Is there a react way of showing a product gallery?

**Comment by aditimadan-Cloudinary** [comment]
We don't have a specific helper method in our React SDK for the Product Gallery Widget, but if you can include external Javascript code into your application, you can open the widget using vanilla Javascript, and can add it to one of your components via its ID. There's more information here about how to initialize it: https://cloudinary.com/documentation/product_gallery#quick_example
There is also a SO link where the other customers have implemented it using React - https://stackoverflow.com/questions/66429792/how-to-implement-cloudinary-product-gallery-in-react-js
