### ISSUE TITLE
client_hints is unknown propType

### ISSUE THREAD

**Issue by rockchalkwushock** [cloudinary/cloudinary-react#23]
Playing around with the library while walking through this [post](http://cloudinary.com/blog/introducing_smart_cropping_intelligent_quality_selection_and_automated_responsive_images) I have found that passing `client_hints` as shown in the article throws an error.

![screen shot 2017-08-02 at 6 51 35 am](https://user-images.githubusercontent.com/19720404/28872587-77d0e5b8-774f-11e7-84e7-cdea61afb6d7.png)

```js
const Photo = () =>
  <Image
    cloudName="turd_ferguson"
    publicId="snl.jpg"
    client_hints="true" // throws error, I have tried just as client_hints as well since it's a Boolean related prop, but still the same result.
  >
    <Transformation gravity="auto" crop="fill" />
    <Transformation dpr="auto" />
    <Transformation width="auto" crop="scale" />
  </Image>

export default Photo
```

I see this at the bottom of the article, so my assumption is I no longer am required to pass this prop to use `client_hints`. Perhaps a better error message should be instated if that is the case?

![screen shot 2017-08-02 at 6 58 21 am](https://user-images.githubusercontent.com/19720404/28872759-2e23f5b2-7750-11e7-9d79-bb864bf46463.png)

**Comment by strausr** [comment]
@rockchalkwushock [Client hints](https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints) is a browser feature.
You can find the browser support matrix [here](http://caniuse.com/#search=client%20hints)

Client hints provide additional data sent from the browser to the backend which can then be utilized to respond with optimized images per the given parameters.

It is an opt-in meta header you should add to your index.html:

`<meta http-equiv="Accept-CH" content="DPR, Viewport-Width, Width">`

The hints are disabled by default and the <meta http-equiv="Accept-CH" content="..."> above serves as an opt-in signal that tells the browser to append the specified headers to outgoing requests (this can be seen in the request header).

**Comment by rockchalkwushock** [comment]
@strausr I see I had never heard of it before. 

As per the last screen shot from that blog post on Cloudinary, it seems that I do not need to pass this prop anymore as this has been setup behind the scenes for the user (or at least that is my understanding). If that is the correct understanding perhaps the message to the user should read something like:

```txt
Proptype `client_hints` has been deprecated as of `cloudinary-react@x.y.z` please refer to the following for more information: <link to the update in that blog post or documentation in the library's docs>
```

Maybe even something in the docs specifying this, I never found anything, perhaps there is something there already.

**Comment by strausr** [comment]
@rockchalkwushock thanks for the feedback! I'll pass this along to the team for consideration.
