### ISSUE TITLE
how to use cloudinary with ant designs upload component?

### ISSUE THREAD

**Issue by yasinnkhann** [cloudinary/cloudinary-react#238]
## Bug report for Cloudinary React SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
I'm trying to use cloudinary to host all the image data for when I make a file upload but I keep getting an uncaught in promise error.
## Describe the desired/expected behavior.
I want to be able  to have successful file upload to my cloudinary server
## Link to reproduction of the issue on codepen/jsfiddle/etc.
https://stackoverflow.com/questions/69060626/how-to-use-cloudinary-with-ant-designs-upload-component

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] UI/Performance - Display or performance issues
[ X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
… if applicable

## Error screenshots
… if applicable

## Browsers (if issue relates to UI, else ignore)
[ X] Chrome
[ ] Firefox
[ ] Safari
[ ] Other (Specify)
[ ] All

## Versions and Libraries (fill in the version numbers)
Cloudinary-core - 0.0.0
Cloudinary-react - 0.0.0
React - 0.0.0
Create-React-App - 0.0.0 / N/A
Babel - 0.0.0
Webpack/Rollup/Other - 0.0.0
Node - 0.0.0
NPM - 0.0.0

## Config Files (Please paste the following files if possible)
Package.json
Webpack.config (if applicable)
Babelrc

## Repository
If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by Vdeub-cloudinary** [comment]
Hi @yasinnkhann,
I see you already opened a case to support@cloudinary.com and my colleague Eric sent some information.
To avoid any confusion and multiple threads, let's keep the conversation on the internal ticket.
Thanks!
