### ISSUE TITLE
Is Cloudinary-react doesn't support for typescript

### ISSUE THREAD

**Issue by phamquoctuan1** [cloudinary/cloudinary-react#240]
i got  that issue : could not find  a declaration file for modules 'cloudinary-react'

**Comment by maoznir** [comment]
Hi @phamquoctuan1 
This is unlikely to be added in the current version,
however we are working on a new major version, which is developed in typescript.

You can see more here:
https://www.npmjs.com/package/@cloudinary/react
https://github.com/cloudinary/js-url-gen
https://github.com/cloudinary/frontend-frameworks#readme

The new react sdk is still in beta, but is coming soon!
