### ISSUE TITLE
TypeError: cld.videoPlayer is not a function

### ISSUE THREAD

**Issue by MZ071999** [cloudinary/cloudinary-react#241]
I want to get the percents viewed from cloudinary's `AdvancedVideo` component and I was following this documentation

https://cloudinary.com/documentation/video_player_events_analytics

but I got this error: 
`TypeError: vid.videoPlayer is not a function`

My code:
```

import { AdvancedVideo } from "@cloudinary/react";
import { CloudinaryVideo } from "@cloudinary/url-gen";

const pubId = props.video.videoPath;
  const vid = new CloudinaryVideo(pubId, { cloudName: "iium" });

  const vplayer = vid.videoPlayer(pubId, { playedEventPercents: [10, 50, 90] });
  vplayer.on("percentsplayed", (event) => {
    console.log(event.eventData.percent + " percents played");
  });

 return (
  
      <div>
        <AdvancedVideo
          cldVid={vid}
          width="100%"
          controls
          innerRef={videoRef}
          playedEventPercents
          onLoadStart={updateViews}
        />
      </div>
)
```

**Comment by maoznir** [comment]
Hi @MZ071999,
The AdvancedVideo component wraps a standard html video element and does not use Cloudinary Video Player.
Please see the [installation and setup](https://cloudinary.com/documentation/cloudinary_video_player#installation_and_setup) documentation of the video player.
