### ISSUE TITLE
expose path by public id

### ISSUE THREAD

**Issue by goldylucks** [cloudinary/cloudinary-react#25]
so we could do:

```jsx
import { imagePath } from 'cloudinary-react'

<img src={imagePath('myImgPublicIdHere')} />
```

My use case is to use this inside rendering markdown:

```
  <ReactMarkdown
    source={`
Some text here ...
![some alt text](${imagePath(myImgPublicIdHere)})
/>`
```

**Comment by eitanp461** [comment]
@goldylucks You can use `cloudinary-core` which is the foundation underlying Cloudinary's React SDK.

Code snippet:

```
import cloudinary from 'cloudinary-core';
const cloudinaryCore = new cloudinary.Cloudinary({cloud_name: 'demo'});

const SampleImg = () => (
    <img src={cloudinaryCore.url('sample')} />
);
```

See full sample [here](https://glitch.com/edit/#!/cloudinary-react-sdk?path=src/app.js:25:0)

**Comment by goldylucks** [comment]
Maybe drop a reference in the docs?

Closing :)

**Comment by eitanp461** [comment]
@goldylucks Thank you for the feedback.
I will pass it along to the documentation team.
