### ISSUE TITLE
How can I used a named transformation for a video?

### ISSUE THREAD

**Issue by nathanl** [cloudinary/cloudinary-react#27]
I have named, eager transformations I've performed on my cloudinary videos. How can I get the video component to render using one of those?

**Comment by strausr** [comment]
@nathanl Eager transformations are executed during the upload process. However, you can use a named transformation to render with your Video tags. For example, <Video .... transformation="my_named_trans"/>

Hope this helps, please let us know if you have any other questions.

**Comment by nathanl** [comment]
`<Video .... transformation="my_named_trans"/>` is what I was looking for! Thanks!

**Comment by nathanl** [comment]
(This would be a good thing to include in the README, IMO.)
