### ISSUE TITLE
Upgrade to react 16

### ISSUE THREAD

**Issue by mvanlonden** [cloudinary/cloudinary-react#29]
warning "cloudinary-react@1.0.3" has incorrect peer dependency "react@^15.3.1".

**Comment by roeeba** [comment]
Hi @mvanlonden. Thank you for pointing it out. Our dev team will handle this as soon as they can.

**Comment by phroz3n** [comment]
@roeeba any updates on this?

**Comment by roeeba** [comment]
Hi @phroz3n, we're aiming to resolve this by mid-December. We will update as soon as this is resolved.

**Comment by raymondAntonio** [comment]
@roeeba,  any news on the react 16 upgrade ? will this be resolved by tomorrow ? just wondering as I'm currently doing my research for a start-up project and just signed up with Cloudinary. can't wait to give it a go in React 16 so I can move on. Thanks mate.

**Comment by roeeba** [comment]
Hi @raymondAntonio. I apologize for the late reply. There's currently no ETA for the upgrade. We will update as soon as there will be.

**Comment by raymondAntonio** [comment]
@roeeba Thank for the updates. All good. apologised for being impatient. that might show how keen  I am to give Cloudinary a go
