### ISSUE TITLE
Error: Maximum call call stack size exceeded

### ISSUE THREAD

**Issue by bernharduw** [cloudinary/cloudinary-react#31]
When I add a Transformation to an Image, the equals function deep compares all the props in `shouldComponentUpdate`. This causes a cycle in React 16 with `_owner`.

cloudinary-react 1.0.4, React 16.

![image](https://user-images.githubusercontent.com/740978/33314280-7404be7e-d42d-11e7-8332-a57b00f812f2.png)

I will provide a workaround as a PR until there is official support for React 16.

**Comment by strausr** [comment]
@bernharduw  Thank you for bringing this to our attention. We will re-evaluate it as part of the upcoming release.

**Comment by bernharduw** [comment]
I also stumbled on a performance issue that is related: With `<Transformation/>` children on the image component, the `componentWillReceiveProps` method takes a very long time to execute (about 6 seconds on my Mac). The reason for this: all the props are passed to the Configuration class in cloudinary-core, which deep-clones them. The _owner attribute of the children prop points to the parent component, so basically the whole React tree is being cloned on every call of `componentWillReceiveProps`.

For now, I have put all the transformation props on the Image component, which also works great. 

But it would make more sense to blacklist `children` or whitelist the valid options before using them in any way.

**Comment by strausr** [comment]
@bernharduw Thank you for the input. We are aware of this and have an open ticket on the issue. I'd be happy to update you as soon as this is resolved.

**Comment by brettgullan** [comment]
+1

I’ve encountered the same issue, though it only arose once I called `this.setState` in another component. For the most part, I’m managing state through Redux, so took a while before this issue became apparent. And a whole lot longer to track down!

Looking forward to a fix for this.

**Comment by eitanp461** [comment]
Fixed by #39
