### ISSUE TITLE
Video component ignores Transformations

### ISSUE THREAD

**Issue by smallstepstoday** [cloudinary/cloudinary-react#35]
Using: React 15.6.2, Cloudinary-React 1.0.4

Using the [React example](https://cloudinary.com/documentation/video_manipulation_and_delivery#quality_control) from the documentation I have the following:
```
import * as React from 'react';
import { shallow } from 'enzyme';
import {Video, Transformation } from 'cloudinary-react';

it('renders the correct url when transformations are specified', () => {
  const video = shallow(
    <Video
      cloudName="dummy-cloud"
      publicId="dog"
    >
      <Transformation quality="50" />
    </Video>
  );
  console.log(video.debug());
  console.log(video.render().html());
});
```
The debug output is as follows:
```
<video>
  <source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.webm" type="video/webm" />
  <source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.mp4" type="video/mp4" />
  <source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.ogv" type="video/ogg" />
  <Transformation quality="50" />
</video>
```
And the final rendered HTML is like so:
```
<source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.webm" type="video/webm">
<source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.mp4" type="video/mp4">
<source src="http://res.cloudinary.com/dummy-cloud/video/upload/dog.ogv" type="video/ogg">
```
No sign of the expected `q_50` in the URL.

Need to have bit_rate, quality and fades for fading in/out.

It's late and it has been a long day, so I am probably doing something wrong. If so, please put an end to my misery. Otherwise, this is a bug!

Best regards,
Dave

**Comment by strausr** [comment]
@smallstepstoday Thank you for this information. I have forwarded the issue to the team for further investigation. In the meantime, you can use a named transformation to set the quality to 50.

Once the named transformation is created you can render your video as the following-

```
 <Video cloudName="dummy-cloud" publicId="dog" Transformation="named_transformation"></Video>
```

Thanks,
Raya
