### ISSUE TITLE
Analytics in Video

### ISSUE THREAD

**Issue by ajmajma** [cloudinary/cloudinary-react#40]
Hello, I am wondering how one can use the analytics, in specific the callbacks from the events. Specifically, the play, pause, and ended events. Is there any reccomended way to do this with your `Video` component. Thanks!

**Comment by ashachak** [comment]
Hi Alex,
Thanks for approaching us. Cloudinary's Video Player will meet all your needs and much more! Our player can be initiated with a single line of code that accepts a video ID and automatically builds video manipulation and delivery URLs.
Among other things, it enables you to capture in-depth analytical data about your video audience and their consumption of your videos.
For further details please refer to https://cloudinary.com/documentation/cloudinary_video_player and https://cloudinary.com/blog/the_developer_friendly_video_player_that_truly_delivers
Please don't hesitate to contact us for any further question.
Thanks
Amit

**Comment by ajmajma** [comment]
Hey Amit, thanks for your response. As far as I am aware,  you don't do this step when using this react component -

     `var vplayer = cld.videoPlayer("my-video"});

       vplayer.on('ended', (event) => {
         ....
    `
Instead, with the video component from this repository, it's

           `   <Video
              className="cld-video-player  cld-fluid"
              id="cld-video-desktop"
              cloudName="cloudName"
              publicId="id"
              controls
              poster="posterUrl"
              />`

What I am wondering is with this react component, how does one tap into the analytics events? 
 Thanks!

**Comment by tocker** [comment]
Hi @ajmajma,

You can pass event handlers to the Video component as you would to any React component. For example,

```
let handlePlay = (e)=>{
  console.log("Play event:", e);
};

// ...
render(
  <Video cloudName="demo" controls publicId="dog" width="300" crop="scale" onPlay={(e)=> handlePlay(e)}/>
)
```

or

```
let handlers = {
  onPause: (e)=> console.log("Pausing at ", e.target.currentTime),
  onSeeked: (e)=> console.log("Seeked to new time: ", e.target.currentTime)
};
render(
  <Video {...handlers} cloudName="demo" controls publicId="dog" width="300" crop="scale"/>
)
```

Hope this helps!

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by wilsonmsalberto** [comment]
Hello! I'm currently trying to use the Video component but similar to the initial question, I'm unable to understand how to properly use `analytics: true`.

Any pointers?

**Comment by maoznir** [comment]
Hi @wilsonmsalberto if you're using the Cloudinary Video Player (not cloudinary-react SDK), then please see here: https://cloudinary.com/documentation/video_player_events_analytics or contact Cloudinary's support at https://support.cloudinary.com/hc/en-us

**Comment by wilsonmsalberto** [comment]
Hello @maoznir I'm currently working within a React project and will need to customize the Video Player as well as have analytics.

Does your comment mean that I cannot use `cloudinary-react` if I wish to have Analytics?
If not, Is there a suggested approach to using Cloudinary Video Player within a React project?

**Comment by maoznir** [comment]
@wilsonmsalberto please see this blog post about integrating the cloudinary video player in react:
https://dev.to/rebeccapeltz/five-ways-for-integrating-the-cloudinary-video-player-into-react-applications-2kcb
