### ISSUE TITLE
Transformation causing application to be unresponsive

### ISSUE THREAD

**Issue by tooppaaa** [cloudinary/cloudinary-react#43]
Hi,

I installed the latest package: "cloudinary-react": "1.0.6" and still have issues with transformations.

The following is working :
```
<Image publicId={publicId}>
</Image>
```

When this is not
```
<Image publicId={publicId}>
        <Transformation width="100" crop="scale" angle="10" />
</Image>

```
There are no errors in the console.

**Comment by eitanp461** [comment]
@tooppaaa thank you for the report.
Can you provide more information? 
- What exactly do you see? 
- Is there anything in the generated HTML?

I created a Glitch project with your sample code which seems to work. Can you remix it and reproduce the error?
https://glitch.com/edit/#!/cloudinary-react-sdk-testing?path=src/app.js:1:0

**Comment by tooppaaa** [comment]
Hmm I am confused now. I tried to reproduce in your glitch but it worked without problems.
https://glitch.com/edit/#!/bubble-plant.

It's maybe due to some conflicts with other packages.
I'll investigate a bit more and reopen this if I get more info.
