### ISSUE TITLE
Signed URLs

### ISSUE THREAD

**Issue by hiredgun** [cloudinary/cloudinary-react#45]
Is it possible to sign somehow dynamic URLs using components from this lib? I mean use case with auto width taken dynamically from images' container on a client side. I made some debugging but didn't find anything. I guess that it's possible with SDK but probably only with static URLs which can be signed before moving an app to prod since appSecret can't be exposed to app clients.

**Comment by d-mendoza** [comment]
@hiredgun Signed URLs only supported on server-side SDKs as not expose the api_secret.

**Comment by hiredgun** [comment]
@d-mendoza thx, that's what I thought :)
