### ISSUE TITLE
Rendering only the children with no additional div

### ISSUE THREAD

**Issue by adregan** [cloudinary/cloudinary-react#48]
It seems that there isn't a reason to render an additional `div` in the [`ClodinaryContext` component](https://github.com/reactjs/react-redux/blob/master/src/components/Provider.js#L36), and that the component could instead simply render the children (similar to the [react-redux `Provider`](https://github.com/reactjs/react-redux/blob/master/src/components/Provider.js#L36)). 

This would have the benefit of not needing to explicitly set the height to 100 for pages wrapped in the context and save us one level of nesting.

If interested, I'd be happy to open a PR for this.

**Comment by strausr** [comment]
@adregan Thanks for bringing this to our attention. I've taken this internally and will update you once this change is made.

**Comment by maoznir** [comment]
Closing as this was handled in https://github.com/cloudinary/cloudinary-react/pull/81
