### ISSUE TITLE
width: auto and containerwidth comma-size

### ISSUE THREAD

**Issue by runar-rkmedia** [cloudinary/cloudinary-react#49]
If the container of `Image` is a value of any decimal-number, the image will not show at all. This could easily be fixed by rounding the width, but currently this library does not do that.

Currently, in one of my containers, it will produce a link link this:

`https://res.cloudinary.com/account/image/upload/c_scale,dpr_2.0,f_auto,q_auto,w_143.5/image`

**Comment by strausr** [comment]
@runar-rkmedia Note that Float values are used to indicate a relative resizing (e.g. w_0.5 for half the width of the input image). You're not seeing the image with w_143.5 since the resulting image is too large.

**Comment by runar-rkmedia** [comment]
I understand. Either way, floats for the container-width will break this. I've submitted a fix for it.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by Halling69** [comment]
Hi,

This merge is highly relevant to make width:auto work with the react component
