### ISSUE TITLE
Multiple Images with Transformation causes page to almost crash

### ISSUE THREAD

**Issue by paschaldev** [cloudinary/cloudinary-react#53]
I have a page that loops through 12 items and renders and `Image` with `Transformation`, this blocks the rendering of other items and I get the "Unresponsive Script" warning from firefox, this causes my entire page to hang for 10-15seconds and almost rendered unresponsive.

I already set my context. I have a component like this 

### UserList.js
```jsx
import { Image, Transformation } from 'cloudinary-react'

const UserList = (props) => {

	return(
		<div className="flex items-center py-2 border-grey-lighter border-b">
			<div className="" style={ { width: '50px' } }>
				<Image publicId={ props.user.meta.avatar } >
					<Transformation radius="max" width="35" height="35" crop="scale" />
				</Image>
			</div>
			<div className="">
				<p>{ props.user.name }</p>
				<small className="text-grey">{ props.user.email }</small>
			</div>
		</div>
		)
}

export default UserList
```

I use this component like this: 

### user_info.js 

```jsx 
<div className="p-6">
{
 		user.connections.map( (user, index) =>  
 			<Link route="user_info" params={{ id: user.id }} key={index} >
 				<a className="block text-grey-darker">
 					<UserConnectionList user={user} />
 				</a>
 			</Link>
 			)
 	}
</div>
```

This is a huge performance issue I had to disable the Image with Transformation.

**Comment by strausr** [comment]
@paschaldev Can you please elaborate on what versions you're using and if there is a live page we can take a look at?

**Comment by paschaldev** [comment]
"cloudinary-react": "^1.0.6",

It's not live yet. I'm working on localhost. I'm using Next.js framework also

**Comment by strausr** [comment]
Unfortunately, we're unable to reproduce this on our end. Can you please share with us your project so that we can take a closer look? If privacy is an issue please feel free to open a ticket at support@cloudinary.com

**Comment by paschaldev** [comment]
I understand. I will close this for now and when I have a better repo to put out, will re-open.
