### ISSUE TITLE
Full page hero video

### ISSUE THREAD

**Issue by skube** [cloudinary/cloudinary-react#56]
Would one use this component library to create the full page hero background effect popularly seen on many websites these days?

**Comment by skube** [comment]
Something like what Pepsi does: https://www.pepsi.com/en-us/

**Comment by strausr** [comment]
We currently don't have such a feature. That being said, we'll update if it is added to our roadmap.

**Comment by strausr** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
