### ISSUE TITLE
Don't render on empty string for this.state.url

### ISSUE THREAD

**Issue by lisamartin00** [cloudinary/cloudinary-react#58]
We are noticing some flash of broken images on page load.

The `<img>` is rendered even when `this.state.url` is empty, so you briefly get
`<img src="" />`,
which will flash a broken image in Chrome before rendering the correct one.  (The broken image is showing up if you have a fixed width/height wrapper around your image).

Checking the length of `this.state.url` before returning the `<img>` in `render()` should fix this issue.

I can put in a PR for this soon.

**Comment by lisamartin00** [comment]
Whoops - I was mistaken.  The fixed width/height issue is not on a wrapper, but on the image itself.  

Here's a codepen to reproduce the issue:
https://codepen.io/lisamartin00/project/editor/ZBjYwr

**Comment by lisamartin00** [comment]
I've submitted a PR for this: https://github.com/cloudinary/cloudinary-react/pull/59

**Comment by goldenshun** [comment]
@shirlymanor @tocker Any updates on PR https://github.com/cloudinary/cloudinary-react/pull/59?  The broken images are a large problem for us and the fix seems fairly simple.
