### ISSUE TITLE
Normal HTML attributes aren't being applied correctly

### ISSUE THREAD

**Issue by webbower** [cloudinary/cloudinary-react#6]
When I use the `Image` component and I pass in normal HTML attributes, including native event handlers, they are getting converted to snake case inside the `Image` component and so they are ignored by React's `img` component (attributes and handlers aren't being applied properly to the resulting HTML element). You can see what I'm talking about in the attached screenshot of the React dev tools.

![developer_tools_-_http___localhost_3000_products_my-product-3_trk_vendor_dashboard_products_panel](https://cloud.githubusercontent.com/assets/602913/21597275/c053bc06-d0fc-11e6-9a9b-537b3090366a.png)

My suspicion is that the function call on this line https://github.com/cloudinary/cloudinary-react/blob/master/src/components/Image/Image.js#L107 is not handling the React-style of camel case attributes correctly. And there doesn't seem to be any notes on how to specially handle native HTML attributes in the docs for this component.

**Comment by tocker** [comment]
Hi @webbower, thanks for reporting this!
I verified the issue and a fix will be posted soon.

**Comment by webbower** [comment]
@tocker Awesome! Thanks.
