### ISSUE TITLE
Need help creating Typescript typings for cloudinary-react

### ISSUE THREAD

**Issue by inunotaisho26** [cloudinary/cloudinary-react#63]
I am posting this issue here for others if they'd like to help. I am working to create typescript typings for `cloudinary-react` as I use `.tsx` when writing a `React` app. Catches bugs pretty quickly.

Repo i have forked: https://github.com/inunotaisho26/cloudinary-react.

**Comment by roeeba** [comment]
Hey @inunotaisho26. Thanks for sharing!
