### ISSUE TITLE
Folder names to the publicId property used in Image component breaks url

### ISSUE THREAD

**Issue by sverraest** [cloudinary/cloudinary-react#65]
I'm trying to generate a URL to a cloudinary image by passing the folder appended to the publicId in the "publicId" property of <Image>.

This process is described here for the generic solution: https://support.cloudinary.com/hc/en-us/articles/202520902-Can-I-create-folders-in-my-Cloudinary-account-

The <Image> component however puts this at the end after any manipulations so not immediately after /upload, this gives an incorrect URL.

**Comment by JulianJorgensen** [comment]
@sverraest I had similar issue, but when I referenced the folder name using lowercase then it worked.

E.g. `publicId="folderhere/image.jpg"`

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
