### ISSUE TITLE
Forcing a new version

### ISSUE THREAD

**Issue by skube** [cloudinary/cloudinary-react#69]
When replacing an image or video with a new uploaded version, how does one specify the version in this component? Simply replacing the asset won't immediately update as the asset is cached.

**Comment by Halling69** [comment]
Hi if you read this article: https://support.cloudinary.com/hc/en-us/articles/202520852-I-ve-replaced-an-existing-image-with-a-new-one-but-my-website-still-shows-the-old-one-Why-is-that-  you will see that you should use the version tag, described here: https://support.cloudinary.com/hc/en-us/articles/202520912-What-are-image-versions-

Alas, version is not (yet) a supported property of the module

**Comment by Halling69** [comment]
looks like yo can do: 
            <Image
                  className="card-img-top"
                  alt="foo bar "
                  cloudName="yourcloud"
                  publicId={imageId}
                  **option= {{version = cloudinaryVersion}}**
                  crop="pad"
                  width={width}
                  height={height}
                  responsive = "true"
                  fetch_format="auto"
                />

**Comment by Halling69** [comment]
just use the version option, it not documented but it is working:
 <Image
          id={publicId}
          className="some-css-class"
          alt={alt}
          cloudName="some_cloud"
          resource_type={"image"}
          publicId={publicId}
          **version= {cloudinaryVersion}**
          crop="pad"
          dpr="auto"
          responsive
          width="68"
          height="68"          
          fetch_format="auto"
        />
