### ISSUE TITLE
Support for react-native

### ISSUE THREAD

**Issue by ScreamZ** [cloudinary/cloudinary-react#71]
Hello,

First I would like to say good job for this library, seems being full of good react practices.

I would like to use this library with `react-native`. I think it's a simple conditional on using `<Image>` component instead of web `<img>` component. Nothing harder (I might be wrong), this can be prototyped using https://snack.expo.io.

(react-native is shipped with a `fetch` polyfill.)

Can we expect something like this in a near future ?

Best regards

**Comment by strausr** [comment]
Thanks for the kind words:) We currently don't have an ETA for a react native library. However, we'll update here if this changes in the future.

**Comment by joelgetaction** [comment]
+1 for React Native support.  We really want to use Cloudinary in a large project, but lack of React Native support is holding us back from using Cloudinary ...

**Comment by ScreamZ** [comment]
I think this can be pretty easy, just checking context and replace `img` by `Image`. Maybe more difficult when using responsiveness.

In fact you can make one component on your own using the SDK. Not too hard.

**Comment by micahkatz** [comment]
@ScreamZ how are you planning on accomplishing this in RN? I have the same problem, and can either figure out how to do this in react native or make react native make a request to my server, which then requests to Cloudinary. I want to make this the most efficient possible

**Comment by ScreamZ** [comment]
Just use this: https://github.com/cloudinary/pkg-cloudinary-core

Make a component, that will render an Image component using the generated url

**Comment by micahkatz** [comment]
@ScreamZ Thank you for responding. I can definitely get that working now, but I am now concerned about compression. Does it compress the photos automatically?

**Comment by ScreamZ** [comment]
@micahkatz Not automatically, as you can read on the client documentation you can pass some parameters, one good practice is to define named transformations on cloudinary back-office and you can pass them as parameter while generating the URL with the frontend client.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
