### ISSUE TITLE
Video component for adaptive bit rate streaming

### ISSUE THREAD

**Issue by ricByte** [cloudinary/cloudinary-react#72]
Hi,
i'm trying to use your component for Videos with adaptiveBitRate format(mpd).
It's possible?
This is an example of how I use it
Thanks

```
<Video cloudName={'cloudName'}
       publicId={'urlvideo'} controls={true}
       cdnSubdomain={true}
       muted={true}
       privateCdn={true}
       secure={true}
       streamingProfile={'full_hd'}
       videoCodec={''}
       format={'mpd'}>
  <Transformation quality="50" width="300" height="200"/>
</Video>
```

**Comment by shirlymanor** [comment]
Hi,
I'm sorry for the late response!

Cloudinary does support MPEG-DASH.

Here is detailed information for your review: 
https://cloudinary.com/documentation/video_manipulation_and_delivery#adaptive_bitrate_streaming_hls_and_mpeg_dash

Hope that helps
