### ISSUE TITLE
TypeScript definition support?

### ISSUE THREAD

**Issue by tangentlin** [cloudinary/cloudinary-react#74]
Could we have official support of TypeScript definition for this excellent component?  I am aware of previous effort as in #63 , but having official TS backing would help adapt to larger project efforts.  Thanks!

**Comment by roeeba** [comment]
Hey @tangentlin. Thanks for the feedback! Glad you like our work :)
Please see our comment here - https://github.com/cloudinary/cloudinary_npm/issues/175#issuecomment-434718369.
Updates to follow.

**Comment by ScreamZ** [comment]
I agree with the comment you linked, but it's also in your interest to update the user experience for your product, you can rely on community for support but you can delegate everything to them.

I'm not flaming, I'm just trying to find a nice compromise for everybody :) We can work together hand in hand on that case if you would like so.

Regards

**Comment by 2ajoyce** [comment]
If anyone ends up here and is as confused about the current state of the typings as I am, here are the typings I wrote up since there aren't official ones. https://pastebin.com/uM0RRJGb

@roeeba If there's a better way for me to get typings for cloudinary-react, or help make them, let me know. I couldn't find one.

**Comment by pawelotto** [comment]
> If anyone ends up here and is as confused about the current state of the typings as I am, here are the typings I wrote up since there aren't official ones. https://pastebin.com/uM0RRJGb
> 
> @roeeba If there's a better way for me to get typings for cloudinary-react, or help make them, let me know. I couldn't find one.

LEGEND!

**Comment by imbsky** [comment]
+1

**Comment by imbsky** [comment]
Here is auto generated definition by dts-gen.
https://gist.github.com/imbsky/2a7aa54cb26fcce346d7bcb3f87f441c

**Comment by nyze2oo9** [comment]
I debugged this [line of code](https://github.com/cloudinary/cloudinary-react/blob/28ae46122ccb40a30bf1be0065aec24da25abb6c/src/components/CloudinaryComponent/CloudinaryComponent.js#L119) and noticed that the CloudinaryComponent can get all of these [Types](https://github.com/cloudinary/pkg-cloudinary-core/blob/464666e905d07902a6763abc7d9678af60db79b2/cloudinary-core.d.ts#L285), but in camelCase.  All other components extend the CloudinaryComponent, so I created minimal Types until the official ones are released. For an official release it would be great to have specific types for image and video. 

[React Types](https://gist.github.com/nyze2oo9/3be8cb198109c805396594c89d84edee)

**Comment by kevinclarkadstech** [comment]
Ugh, I just saw there are no types for this library.  I suggest reopening this if you want people to use Cloudinary....after all, it is 2021 now and having no TypeScript definitions on a library for a paid service is pretty poor.

**Comment by patrick-tolosa** [comment]
@kevinclarkadstech We understand the community's needs for typed support, and we agree that modern libraries must contain type definitions.

We are on the verge of releasing our new generation of JS SDKs (Currently in Beta), which offers type definitions, tree shaking, and a better, more well-rounded API.

You can see more here:
- [Official Documentation](https://cloudinary.com/documentation/javascript2_integration)
- [The Base SDK responsible for Transformations ](https://github.com/cloudinary/frontend-frameworks)
- [The Frameworks monorepo currently containing Angular and React](https://github.com/cloudinary/frontend-frameworks)

**Comment by alicercedigital** [comment]
We are waiting for the types too, today almost every project we start have typescript.

**Comment by kevinclarkadstech** [comment]
> @kevinclarkadstech We understand the community's needs for typed support, and we agree that modern libraries must contain type definitions.
> 
> We are on the verge of releasing our new generation of JS SDKs (Currently in Beta), which offers type definitions, tree shaking, and a better, more well-rounded API.
> 
> You can see more here:
> 
> * [Official Documentation](https://cloudinary.com/documentation/javascript2_integration)
> * [The Base SDK responsible for Transformations ](https://github.com/cloudinary/frontend-frameworks)
> * [The Frameworks monorepo currently containing Angular and React](https://github.com/cloudinary/frontend-frameworks)

@patrick-tolosa great!  I will be excited to see.

**Comment by andrelandgraf** [comment]
I hope the types for React make it into npm soon. First time I actually have to define a d.ts file by myself. I hope this helps others:

```typescript
interface CloudinaryContextProps {
    cloudName: string;
}

interface ImageProps extends JSX.IntrinsicElements.img {
    publicId: string;
    crop: string;
}

interface VideoProps extends JSX.IntrinsicElements.video {
    publicId: string;
}

interface TransformationProps {
    quality: string;
}

declare module 'cloudinary-react' {
    class CloudinaryComponent {
        constructor(props, context) {}

        getChildContext() {}

        render() {}

        getChildTransformations(children) {}

        getTransformations() {}

        normalizeOptions(...options) {}

        getURL(extendedProps) {}

        typesFrom(configParams) {}
    }

    export const CloudinaryContext: React.FC<CloudinaryContextProps>;

    export const Image: React.FC<PropsWithChildren<ImageProps>>;

    export const Video: React.FC<PropsWithChildren<VideoProps>>;

    export const Transformation: React.FC<TransformationProps>;
}
```

**Comment by eyalktCloudinary** [comment]
@andrelandgraf Thank you for sharing the typing for others to see!
Note, that in our JS v2 SDKs, TS typing is included out of the box. Additional information can be found here -
https://cloudinary.com/documentation/javascript2_integration

**Comment by andrelandgraf** [comment]
Does this also apply for the react package?

I installed the latest version from npm and there were no types included.

**Comment by patrick-tolosa** [comment]
@andrelandgraf  - This package (Cloudinary-react) will not contain type definitions, as mentioned above we are working on a new version of this package that will be written in typescript.

**Comment by heyitstowler** [comment]
> I hope the types for React make it into npm soon. First time I actually have to define a d.ts file by myself. I hope this helps others:
> 
> ```ts
> interface CloudinaryContextProps {
>     cloudName: string;
> }
> 
> interface ImageProps extends JSX.IntrinsicElements.img {
>     publicId: string;
>     crop: string;
> }
> 
> interface VideoProps extends JSX.IntrinsicElements.video {
>     publicId: string;
> }
> 
> interface TransformationProps {
>     quality: string;
> }
> 
> declare module 'cloudinary-react' {
>     class CloudinaryComponent {
>         constructor(props, context) {}
> 
>         getChildContext() {}
> 
>         render() {}
> 
>         getChildTransformations(children) {}
> 
>         getTransformations() {}
> 
>         normalizeOptions(...options) {}
> 
>         getURL(extendedProps) {}
> 
>         typesFrom(configParams) {}
>     }
> 
>     export const CloudinaryContext: React.FC<CloudinaryContextProps>;
> 
>     export const Image: React.FC<PropsWithChildren<ImageProps>>;
> 
>     export const Video: React.FC<PropsWithChildren<VideoProps>>;
> 
>     export const Transformation: React.FC<TransformationProps>;
> }
> ```

This helped me!

**Comment by igdev116** [comment]
You saved me!
