### ISSUE TITLE
Images loading as a broken image

### ISSUE THREAD

**Issue by nate770** [cloudinary/cloudinary-react#75]
A little bit of background first

I'm displaying images stored in a private s3 bucket using auto upload in the url
Relevant Links: https://cloudinary.com/documentation/fetch_remote_images#auto_uploading_with_on_the_fly_transformations
https://support.cloudinary.com/hc/en-us/articles/203276521-How-do-I-allow-Cloudinary-to-read-from-my-private-S3-bucket-

Everything was working alright when I was manually creating the url myself and dropping it in an img tag, something like this
`<img src="http://res.cloudinary.com/dp9dnliwc/image/upload/c_lpad,dpr_2.0,h_300,w_219/v1/wmmedia/watch_images/large/10097_1482181335.jpg`

When using this library, I get all my images showing up as broken for a few seconds until they load, I can't seem to replicate it properly in codepen, but I've pasted the raw code from the component here.
https://codepen.io/nate770/pen/EObgaW

` <Image
                cloudName="dp9dnliwc"
                publicId={image_link}
                width="auto"
                fetchFormat="auto"
                height={w > 500 ? '300' : '250'}
                crop="lpad"
                responsive
                dpr="auto"
              />`

I've uploaded an image of what I see, and if you go to this link, and press next on the pagination, you might see the same thing
http://dev.watchmaxx.com/mens-watches?page=6
<img width="992" alt="screen shot 2018-11-19 at 2 37 48 pm" src="https://user-images.githubusercontent.com/8770029/48731304-bc6eb480-ec0a-11e8-9023-1f02bfc4fb03.png">

**Comment by divsbhalala** [comment]
i am also getting same error for big size image 
![image](https://user-images.githubusercontent.com/12185309/49864703-14bf5d80-fe29-11e8-966f-9a5344acef5b.png)

**Comment by strausr** [comment]
@nate770 
The problem here is that responsive images width is currently calculated by Javascript, delaying the setting of the actual value for the <img>’s src attribute.

During that time when <img> is rendered to the HTML but without a valid src it shows up as a broken image, see https://codepen.io/eitanp461/pen/dQZKYr

A possible solution for this is to hide the image until it loads using its onload callback, e.g. see https://codesandbox.io/s/ww199yor95.

**Comment by strausr** [comment]
@divsbhalala This is not enough information to asses why your image is nor rendering. Please provide more information on your implementation as well as the URL you're using.

**Comment by divsbhalala** [comment]
@strausr Thanks for reply i just fixed this issue by adding this line on component source file 
`render() {
    var {publicId, responsive, responsiveDebounce, children, ...options} = CloudinaryComponent.normalizeOptions(this.props,
      this.context);
    var attributes = cloudinary.Transformation.new(options).toHtmlAttributes();
    if (!this.state.url) {
      return
    }
    return (
      <img {...attributes} src={this.state.url} ref={(e)=> {this.element = e;}}/>
    );
  }`

**Comment by strausr** [comment]
Updating that issue is related and has been fixed in-https://github.com/cloudinary/cloudinary-react/releases/tag/1.1.0
