### ISSUE TITLE
Does order of image params matter?

### ISSUE THREAD

**Issue by wwaterman12** [cloudinary/cloudinary-react#76]
We get the following successes/failures in rendering cloudinary images in our env and I don't understand why they should/shouldn't work:

```js
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/h_39,q_auto,w_33/v1/${image_path}` // FAIL
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/h_38,q_auto,w_33/v1/${image_path}` // FAIL
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/h_37,q_auto,w_33/v1/${image_path}` // OK
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/q_auto,h_39,w_33/v1/${image_path}` // OK
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/h_39,w_33,q_auto/v1/${image_path}` // OK
const imgUrl = `http://res.cloudinary.com/${account}/image/upload/f_auto,h_39,q_auto,w_33/v1/${image_path}` // OK
```

Does order of image params matter? Am I missing something in how `width`,`height`, and `quality` affect one another?

**Comment by yakirp** [comment]
Could you please share a full image URL for example? (one that fails)

**Comment by wwaterman12** [comment]
@yakirp Apologies if this isn't the right channel for this type of issue as it's more related to cloudinary in general instead of React specifically.

But here is the example URL I used with the above successes and failures (with this one being one of the failures):
- http://res.cloudinary.com/hstcxjula/image/upload/h_39,q_auto,w_33/top_destinations/tokyo

**Comment by wwaterman12** [comment]
@yakirp Thank you for your quick response.

I've actually had the same issue with both adding `v1` and not adding it but can't seem to reproduce consistent successes/failures one way or the other.

But one thing that I don't understand - if `X-Cld-Error: Invalid transformation parameter - top` is really the issue, then why would the order of the parameters affect whether it loads properly or not?

```
http://res.cloudinary.com/hstcxjula/image/upload/h_39,q_auto,w_33/top_destinations/tokyo - doesn't work
http://res.cloudinary.com/hstcxjula/image/upload/q_auto,h_39,w_33/top_destinations/tokyo - works
```

**Comment by yakirp** [comment]
So I checked this internally, and we think that there is an issue on our end about that. 
Using such URLs (with the "_") should not work, you must always use the `v1`.

I will keep you posted, meanwhile please deliver your images only with `v1`.

Cheers

**Comment by yakirp** [comment]
Hi
I'm checking the issue with the team, I will keep you posted.

--Yakir

**Comment by yakirp** [comment]
Hey @wwaterman12 ,
I'm so sorry for missing this, my bad. 
Is this still relevant?

Thanks,
Yakir

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
