### ISSUE TITLE
Transformation component bug

### ISSUE THREAD

**Issue by laurisbernhart** [cloudinary/cloudinary-react#82]
When I include the <Transformation/> tag, the page renders about 1 second slower! 

I don't think that the props are wrong, because it actually renders - just really slow.

Do you think you can solve that in the upcoming time? 

Otherwise I will probably use cloudinaryCore to build up the url string and use a normal img tag. Or do you have any better solution?

![image](https://user-images.githubusercontent.com/10515029/54561333-b1fbd600-49c4-11e9-8c3d-378a5ab83a97.png)

Best Lauris

**Comment by d-mendoza** [comment]
Is this for a resource that is being accessed for the first time? Is this slowness observed when the same resource is accessed again?

**Comment by laurisbernhart** [comment]
Hi @d-mendoza ,

sorry for my late reply - I did not receive any notification that you answered. 

Slowness is observed always! Even if the image is pulled from cache.

Best Lauris

**Comment by d-mendoza** [comment]
After running some initial tests, everything seems to load as expected and within a reasonable about of time < 1 second. We may need you to share more details like:

- Cloud name?
- What are the public_id of the resources?
- How many images are loaded on the same page?
- Where is your account making these requests from? Do you have a live page that we can view how long it loads?
- Can you create a JSFiddle with React showing this behavior?

I know that some personal details may be shown here, but if you wish, you can open a support ticket https://support.cloudinary.com/hc/en-us/requests/new and we can continue the correspondence for privacy reasons.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
