### ISSUE TITLE
Is there a different way to use the directory structure?

### ISSUE THREAD

**Issue by SinYooDong** [cloudinary/cloudinary-react#83]
# Question
----
I have Specific images in my Cloudinary by directorying them.

The code below shows the image normally.
```
<Image cloudName="mycloud" publicId={"iwpkwptlhv6c0nxvw2pf"} crop="scale" />
```
However, the following code will receive 404.
```
<Image cloudName="mycloud" publicId={"iwpkwptlhv6c0nxvw2pf"} width="680" height="400" crop="scale" />
```

[url made by SDK.]

http://res.cloudinary.com/mycloud/image/upload/c_scale,h_400,w_680/zbtlrsyb5xqr7kvbw0b4
[actual required url]
http://res.cloudinary.com/mycloud/image/upload/c_scale,h_400,w_680/mySpecific/zbtlrsyb5xqr7kvbw0b4

Images that wanted to be processed seemed to want directory path.

Do you have any settings that I can use correctly?

thank you

**Comment by strausr** [comment]
Can you share with me your cloudname so that I can take a look? You can also open a ticket at support@cloudinary.com if you don't want to share this information publicly.

**Comment by SinYooDong** [comment]
Thank you for your answer. I will search again and send a mail.
