### ISSUE TITLE
Default "poster" value for Video is incorrect

### ISSUE THREAD

**Issue by mattjennings** [cloudinary/cloudinary-react#86]
The documentation for `poster` under the [Embedding videos in web pages](https://cloudinary.com/documentation/video_manipulation_and_delivery#embedding_videos_in_web_pages) section suggest that the default poster should be "the middle frame of the source video in jpg format". However, it looks like it is instead the first frame of the video. Additionally, it shows a blank/white poster on iOS devices (tested on iOS 12.2).

Here is a [CodeSandbox](https://codesandbox.io/s/v0xm19nvx5) that demonstrates the problem.

**Comment by strausr** [comment]
Thanks for bringing this to our attention.

**Comment by winstonma** [comment]
Yes I have having the same issue. I have to manually add the url in `poster` in order to get it work. I assumed that the poster is given by default.

**Comment by maoznir** [comment]
Hi @winstonma,
Thanks again for bringing this to our attention,
We'll release a fix for this very soon, I'll update when we do.

**Comment by maoznir** [comment]
Hi @mattjennings @winstonma,
We've released version 1.3.3 with a fix for the default video frame.
Please let us know if this solves the issue for you.

**Comment by winstonma** [comment]
@maoznir Thanks it works flawlessly.

Just a very quick question, the webm version of my video is a bit blurry. Just wonder if it is possible to provide just the mp4 version?

**Comment by maoznir** [comment]
Hi @winstonma,
you can pass a "sourceTypes" param that can be an array of strings or a string:
<Video cloudName="demo" publicId="dog" sourceTypes="mp4" />
or
<Video cloudName="demo" publicId="dog" sourceTypes={["mp4"]} />

**Comment by winstonma** [comment]
Thanks @maoznir
