### ISSUE TITLE
Cloudinary React and Bootstrap both use the <Image> component name

### ISSUE THREAD

**Issue by conorpirie** [cloudinary/cloudinary-react#9]
I'm using bother Cloudinary React and React Bootstrap and have come across a conflict with the <Image> component 

`import { Image } from 'react-bootstrap';`
`import { Image } from 'cloudinary-react';`

Is there a good way to solve this? I've considered:
- Changing the name of Image in cloudinary react manually.
- Importing the cloudinary Image component into a separate sub-component, then importing that component normally.

Thanks in advance!

**Comment by eitanp461** [comment]
@conorpirie You can use an alias when importing, e.g.

```javascript
import { Image } from 'react-bootstrap';
import { Image as CloudinaryImage } from 'cloudinary-react';
```

And then use it as follows:
```javascript
<CloudinaryImage cloudName="demo" publicId="sample" width="300" crop="scale"/>
<Image src="https://react-bootstrap.github.io/assets/logo.png"/>
```

**Comment by conorpirie** [comment]
Awesome, thank you!
