### ISSUE TITLE
upload widget custom border-radius

### ISSUE THREAD

**Issue by mikestaub** [cloudinary/cloudinary-react#91]
How can I apply arbitrary styles to the upload widget? We want it to match the theme of our website.

**Comment by shirlymanor** [comment]
@mikestaub You might want to use our demo page to match the best theme to your website here: https://demo.cloudinary.com/uw/ (it generate the code by the theme that you choose).

**Comment by mikestaub** [comment]
This api only allows me to change the colors. I want to customize the css of the entire widget. Is there a customCSS config option?

**Comment by shirlymanor** [comment]
@mikestaub It's on our road map to add an option to edit the CSS. However, there is no ETA yet. we will update when will have an ETA.

**Comment by mikestaub** [comment]
@shirlymanor is this feature on the roadmap yet?

**Comment by roeeba** [comment]
Closing this issue as it's not related to our React package. We will update here regardless if and when this will be available.
